import { defineSection } from './define';

export const account = defineSection(
  {
    title: 'Delete your Kuopas account',
    lede: 'You can ask us to delete your account and the data linked to it. This page works without logging in, so you can use it even if you no longer have the app.',
    deletedHeading: 'What is deleted',
    deleted: [
      'Your profile, name and email address',
      'Your messages, posts, comments and community activity',
      'Your bookings, household, roommate and marketplace data',
      'Your verification records and any documents you uploaded',
      'Your inspection records, applications and photos',
    ],
    keptHeading: 'What we may keep',
    kept: 'Rent and lease records that are still running, or that have unpaid charges, must stay with Kuopas for legal and accounting reasons. If you have one, a manager closes your account once it is settled. Reports about content you posted may be kept by moderators for safety.',
    howHeading: 'How to ask',
    how: 'Enter the email address of your account. We send a confirmation link to that address. Opening the link and confirming deletes the account for good.',
    email: 'Email address of the account',
    send: 'Send confirmation link',
    sent: 'If an account exists for that address, a confirmation link is on its way. It works for 24 hours.',
    devLink: 'Development only, no email is configured. Open this link:',
    signedIn: 'You are signed in',
    signedInBody: 'You can delete your account straight away. Type your email address to confirm. This cannot be undone.',
    confirmLabel: 'Type your email address',
    deleteNow: 'Delete my account now',
    confirmTitle: 'Confirm deletion',
    confirmBody: 'This permanently deletes your Kuopas account and the data linked to it. It cannot be undone.',
    confirmButton: 'Yes, delete my account',
    cancel: 'Cancel',
    doneTitle: 'Your account has been deleted',
    doneBody: 'Your account and the data linked to it were removed. Thank you for using Kuopas.',
    contact: 'Questions? Write to customerservice@kuopas.fi or call +358 (0)20 710 9740.',
    errors: {
      email: 'Enter a valid email address.',
      token: 'That link is invalid or has expired. Request a new one.',
      confirm: 'The email address did not match.',
      lease: 'You have a running lease or unpaid charges, so we cannot delete the account automatically. Contact customer service and a manager will close it once it is settled.',
      last_admin: 'This is the only admin account. Give the admin role to someone else first.',
      not_found: 'That account no longer exists.',
    },
    settingsLink: 'Delete my account',
    back: 'Back to Kuopas',
  },
  {
    title: 'Poista Kuopas-tilisi',
    lede: 'Voit pyytää tilisi ja siihen liittyvien tietojen poistamista. Tämä sivu toimii ilman kirjautumista, joten voit käyttää sitä, vaikka sovellus ei olisi enää käytössäsi.',
    deletedHeading: 'Mitä poistetaan',
    deleted: [
      'Profiilisi, nimesi ja sähköpostiosoitteesi',
      'Viestisi, julkaisusi, kommenttisi ja yhteisötoimintasi',
      'Varauksesi, kotitalous-, kämppis- ja kauppatietosi',
      'Vahvistustietosi ja lataamasi asiakirjat',
      'Tarkastuskirjauksesi, hakemuksesi ja kuvasi',
    ],
    keptHeading: 'Mitä voimme säilyttää',
    kept: 'Voimassa olevat tai maksamattomia eriä sisältävät vuokrasopimus- ja vuokratiedot on säilytettävä Kuopaksella lain ja kirjanpidon vuoksi. Jos sinulla on sellainen, isännöitsijä sulkee tilisi, kun asia on selvitetty. Moderaattorit voivat säilyttää turvallisuussyistä ilmoitukset julkaisemastasi sisällöstä.',
    howHeading: 'Näin pyydät',
    how: 'Anna tilisi sähköpostiosoite. Lähetämme vahvistuslinkin kyseiseen osoitteeseen. Linkin avaaminen ja vahvistus poistaa tilin pysyvästi.',
    email: 'Tilin sähköpostiosoite',
    send: 'Lähetä vahvistuslinkki',
    sent: 'Jos osoitteella on tili, vahvistuslinkki on matkalla. Se toimii 24 tuntia.',
    devLink: 'Vain kehitykseen, sähköpostia ei ole asetettu. Avaa tämä linkki:',
    signedIn: 'Olet kirjautunut sisään',
    signedInBody: 'Voit poistaa tilisi heti. Vahvista kirjoittamalla sähköpostiosoitteesi. Tätä ei voi perua.',
    confirmLabel: 'Kirjoita sähköpostiosoitteesi',
    deleteNow: 'Poista tilini nyt',
    confirmTitle: 'Vahvista poisto',
    confirmBody: 'Tämä poistaa Kuopas-tilisi ja siihen liittyvät tiedot pysyvästi. Tätä ei voi perua.',
    confirmButton: 'Kyllä, poista tilini',
    cancel: 'Peruuta',
    doneTitle: 'Tilisi on poistettu',
    doneBody: 'Tilisi ja siihen liittyvät tiedot on poistettu. Kiitos, että käytit Kuopasta.',
    contact: 'Kysyttävää? Kirjoita osoitteeseen customerservice@kuopas.fi tai soita +358 (0)20 710 9740.',
    errors: {
      email: 'Anna kelvollinen sähköpostiosoite.',
      token: 'Linkki on virheellinen tai vanhentunut. Pyydä uusi.',
      confirm: 'Sähköpostiosoite ei täsmännyt.',
      lease: 'Sinulla on voimassa oleva vuokrasopimus tai maksamattomia eriä, joten emme voi poistaa tiliä automaattisesti. Ota yhteyttä asiakaspalveluun, niin isännöitsijä sulkee sen, kun asia on selvitetty.',
      last_admin: 'Tämä on ainoa ylläpitäjän tili. Anna ylläpitäjän rooli ensin jollekin toiselle.',
      not_found: 'Tiliä ei enää ole.',
    },
    settingsLink: 'Poista tilini',
    back: 'Takaisin Kuopakseen',
  },
);
