import { defineSection } from './define';

export const apply = defineSection(
  {
    nav: {
      overview: 'Apply',
      verify: 'Verify',
      profile: 'Profile',
      pods: 'Pods',
      homes: 'Homes',
      exchange: 'Exchange',
      signOut: 'Sign out',
    },
    title: 'Your housing application',
    lede: 'Find people who live like you, form a verified roommate pod, and apply for a home together.',
    stepDone: 'Done',
    stepTodo: 'To do',
    open: 'Open',
    steps: {
      verify: { title: 'Verify you are a student', body: 'Use your university email or a Suomi.fi login. It keeps every pod made of real students.' },
      profile: { title: 'Tell us how you live', body: 'Eight quick questions about sleep, cleaning, noise and guests.' },
      pod: { title: 'Form a roommate pod', body: 'Invite people who fit, and apply to a shared flat as a group.' },
      apply: { title: 'Apply for a home', body: 'Pick a shared flat or studio that is open for applications.' },
    },
    myApplications: 'Your applications',
    noApplications: 'You have not applied yet.',
    appStatus: {
      submitted: 'Submitted',
      offered: 'Offer received',
      accepted: 'Accepted',
      declined: 'Declined',
      withdrawn: 'Withdrawn',
      rejected: 'Not successful',
      housed: 'Moved in',
    },
    exchangeLink: 'Coming to Kuopio as an exchange student?',
    exchangeLinkBody: 'Apply for temporary furnished housing for your exchange period.',
    // Profile
    profileNeedVerify: 'Verify first, then answer the lifestyle questions.',
    goVerify: 'Verify now',
    // Pods
    podsTitle: 'Roommate pods',
    podsLede: 'A pod is a group of verified students who want to live together. Everyone is checked, and you only see people whose lifestyle fits.',
    needVerify: 'Only verified students can form or join a pod.',
    needProfile: 'Answer the lifestyle questions first so we can measure how well you fit.',
    goProfile: 'Answer the questions',
    createHeading: 'Create a roommate pod',
    podName: 'Pod name',
    podNamePlaceholder: 'For example: Quiet study flat',
    minScore: 'Only suggest people who are at least this compatible',
    create: 'Create pod',
    saved: 'Profile saved. Now create or join a pod.',
    yourPod: 'Your pod',
    members: 'Members',
    memberInvited: 'Invited',
    memberJoined: 'Joined',
    you: 'You',
    organiser: 'Organiser',
    groupFit: 'Group compatibility',
    lowestPair: 'Lowest pair',
    clash: 'Two members clash on a dealbreaker',
    leave: 'Leave pod',
    disband: 'Disband pod',
    remove: 'Remove',
    podFull: 'The pod is full (6 people at most).',
    invitations: 'Invitations',
    invitedTo: 'invited you to the pod',
    accept: 'Join',
    decline: 'Decline',
    findHeading: 'People who fit this pod',
    findLede: 'Verified students without a home, ranked by how well they fit everyone already in the pod. Anyone who breaks a dealbreaker is hidden.',
    findNone: 'Nobody matches yet. Check back as more students join.',
    invite: 'Invite',
    alreadyInvited: 'Invited',
    compatible: 'compatible',
    average: 'average',
    verifiedBadge: 'Verified',
    inPodNote: 'You are in a pod already. Leave it to create a new one.',
    // Homes
    homesTitle: 'Homes open for applications',
    homesLede: 'Only homes that Kuopas has opened are listed. Apply with your pod, or alone for a single room or studio.',
    homesNone: 'No homes are open for applications right now. Check back soon.',
    kinds: { solu: 'Shared flat (soluasunto)', studio: 'Studio (yksiö)', other: 'Apartment', unspecified: 'Apartment' },
    rooms: '{n} rooms',
    free: '{n} free',
    furnished: 'Furnished',
    availableFrom: 'Available from',
    apartment: 'Apartment',
    fit: 'Lifestyle fit with the current flatmates',
    fitNone: 'No flatmate profiles to compare yet',
    tour: 'Photos and videos',
    applyWithPod: 'Apply with my pod',
    applyAlone: 'Apply on my own',
    messagePlaceholder: 'A short note to Kuopas (optional)',
    applied: 'You applied',
    withdraw: 'Withdraw',
    tooBig: 'Your pod is bigger than the free rooms here.',
    notVerified: 'Verify first to apply.',
    podNotReady: 'Everyone in the pod must accept the invitation before you apply.',
    offerBanner: 'Kuopas has offered your pod',
    acceptOffer: 'Accept the offer',
    declineOffer: 'Decline',
    // Exchange
    exchangeTitle: 'Exchange student housing',
    exchangeLede: 'Temporary furnished housing for your exchange period. Apply once, upload your acceptance letter, and Kuopas verifies and allocates rooms in arrival order.',
    homeUniversity: 'Your home university',
    homeCountry: 'Home country',
    arrival: 'Arrival date',
    departure: 'Departure date',
    prefer: 'What would you like',
    preferOptions: { any: 'Whatever is available', solu: 'A room in a shared flat', studio: 'A studio' },
    exchangeMessage: 'Anything we should know (optional)',
    letter: 'Acceptance letter from your Finnish university',
    letterHint: 'PDF or photo. It is only visible to Kuopas staff and is deleted once your application is decided.',
    submitExchange: 'Send application',
    updateExchange: 'Update application',
    exchangeStatus: {
      submitted: 'Received, waiting for review',
      verified: 'Verified, waiting for a room',
      waitlisted: 'On the waiting list',
      allocated: 'A room has been allocated',
      rejected: 'Not successful',
      cancelled: 'Cancelled',
    },
    allocatedTo: 'Your room',
    cancelExchange: 'Cancel application',
    dateError: 'Departure must be after arrival.',
    letterMissing: 'Please upload your acceptance letter.',
    exchangeSaved: 'Application saved.',
  },
  {
    nav: {
      overview: 'Hae',
      verify: 'Vahvista',
      profile: 'Profiili',
      pods: 'Ryhmät',
      homes: 'Kodit',
      exchange: 'Vaihto',
      signOut: 'Kirjaudu ulos',
    },
    title: 'Asumishakemuksesi',
    lede: 'Löydä samalla tavalla asuvia ihmisiä, muodosta vahvistettu kämppisryhmä ja hae kotia yhdessä.',
    stepDone: 'Valmis',
    stepTodo: 'Tehtävä',
    open: 'Avaa',
    steps: {
      verify: { title: 'Vahvista opiskelijastatuksesi', body: 'Käytä yliopiston sähköpostia tai Suomi.fi-tunnistautumista. Näin jokainen ryhmä koostuu oikeista opiskelijoista.' },
      profile: { title: 'Kerro, miten asut', body: 'Kahdeksan nopeaa kysymystä unesta, siivouksesta, melusta ja vieraista.' },
      pod: { title: 'Muodosta kämppisryhmä', body: 'Kutsu sopivia ihmisiä ja hae soluasuntoa ryhmänä.' },
      apply: { title: 'Hae kotia', body: 'Valitse hakuun avattu soluasunto tai yksiö.' },
    },
    myApplications: 'Hakemuksesi',
    noApplications: 'Et ole vielä hakenut.',
    appStatus: {
      submitted: 'Lähetetty',
      offered: 'Tarjous saatu',
      accepted: 'Hyväksytty',
      declined: 'Hylätty',
      withdrawn: 'Peruttu',
      rejected: 'Ei onnistunut',
      housed: 'Muuttanut sisään',
    },
    exchangeLink: 'Tuletko Kuopioon vaihto-opiskelijaksi?',
    exchangeLinkBody: 'Hae tilapäistä kalustettua asuntoa vaihtojaksollesi.',
    profileNeedVerify: 'Vahvista ensin, vastaa sitten elämäntapakysymyksiin.',
    goVerify: 'Vahvista nyt',
    podsTitle: 'Kämppisryhmät',
    podsLede: 'Ryhmä on joukko vahvistettuja opiskelijoita, jotka haluavat asua yhdessä. Jokainen on tarkistettu, ja näet vain sinuun sopivia ihmisiä.',
    needVerify: 'Vain vahvistetut opiskelijat voivat luoda ryhmän tai liittyä siihen.',
    needProfile: 'Vastaa ensin elämäntapakysymyksiin, jotta voimme mitata sopivuuden.',
    goProfile: 'Vastaa kysymyksiin',
    createHeading: 'Luo kämppisryhmä',
    podName: 'Ryhmän nimi',
    podNamePlaceholder: 'Esimerkiksi: Hiljainen opiskelusolu',
    minScore: 'Ehdota vain ihmisiä, jotka sopivat vähintään näin hyvin',
    create: 'Luo ryhmä',
    saved: 'Profiili tallennettu. Luo tai liity nyt ryhmään.',
    yourPod: 'Ryhmäsi',
    members: 'Jäsenet',
    memberInvited: 'Kutsuttu',
    memberJoined: 'Liittynyt',
    you: 'Sinä',
    organiser: 'Järjestäjä',
    groupFit: 'Ryhmän sopivuus',
    lowestPair: 'Heikoin pari',
    clash: 'Kaksi jäsentä on ristiriidassa ehdottoman toiveen kanssa',
    leave: 'Poistu ryhmästä',
    disband: 'Hajota ryhmä',
    remove: 'Poista',
    podFull: 'Ryhmä on täynnä (enintään 6 henkilöä).',
    invitations: 'Kutsut',
    invitedTo: 'kutsui sinut ryhmään',
    accept: 'Liity',
    decline: 'Hylkää',
    findHeading: 'Ryhmään sopivat ihmiset',
    findLede: 'Vahvistetut opiskelijat ilman kotia, järjestettynä sen mukaan, kuinka hyvin he sopivat kaikille ryhmässä oleville. Ehdottoman toiveen rikkovat piilotetaan.',
    findNone: 'Ketään ei vielä sovi. Katso myöhemmin uudelleen.',
    invite: 'Kutsu',
    alreadyInvited: 'Kutsuttu',
    compatible: 'sopii',
    average: 'keskiarvo',
    verifiedBadge: 'Vahvistettu',
    inPodNote: 'Olet jo ryhmässä. Poistu siitä luodaksesi uuden.',
    homesTitle: 'Haettavissa olevat kodit',
    homesLede: 'Listalla ovat vain Kuopaksen avaamat kodit. Hae ryhmälläsi tai yksin yhteen huoneeseen tai yksiöön.',
    homesNone: 'Haettavia koteja ei ole juuri nyt. Katso pian uudelleen.',
    kinds: { solu: 'Soluasunto', studio: 'Yksiö', other: 'Asunto', unspecified: 'Asunto' },
    rooms: '{n} huonetta',
    free: '{n} vapaana',
    furnished: 'Kalustettu',
    availableFrom: 'Vapautuu',
    apartment: 'Asunto',
    fit: 'Elämäntapojen sopivuus nykyisten kämppisten kanssa',
    fitNone: 'Kämppisten profiileja ei vielä ole vertailtavaksi',
    tour: 'Kuvat ja videot',
    applyWithPod: 'Hae ryhmälläni',
    applyAlone: 'Hae yksin',
    messagePlaceholder: 'Lyhyt viesti Kuopakselle (valinnainen)',
    applied: 'Olet hakenut',
    withdraw: 'Peru',
    tooBig: 'Ryhmäsi on suurempi kuin vapaat huoneet täällä.',
    notVerified: 'Vahvista ensin hakeaksesi.',
    podNotReady: 'Kaikkien ryhmässä on hyväksyttävä kutsu ennen hakemista.',
    offerBanner: 'Kuopas on tarjonnut ryhmällesi',
    acceptOffer: 'Hyväksy tarjous',
    declineOffer: 'Hylkää',
    exchangeTitle: 'Vaihto-opiskelijoiden asuminen',
    exchangeLede: 'Tilapäinen kalustettu asunto vaihtojaksollesi. Hae kerran, lataa hyväksymiskirje, ja Kuopas vahvistaa ja jakaa huoneet saapumisjärjestyksessä.',
    homeUniversity: 'Kotiyliopistosi',
    homeCountry: 'Kotimaasi',
    arrival: 'Saapumispäivä',
    departure: 'Lähtöpäivä',
    prefer: 'Mitä toivot',
    preferOptions: { any: 'Mikä tahansa vapaa', solu: 'Huone soluasunnossa', studio: 'Yksiö' },
    exchangeMessage: 'Jotain, mitä meidän pitäisi tietää (valinnainen)',
    letter: 'Suomalaisen yliopiston hyväksymiskirje',
    letterHint: 'PDF tai kuva. Vain Kuopaksen henkilökunta näkee sen, ja se poistetaan kun hakemus on ratkaistu.',
    submitExchange: 'Lähetä hakemus',
    updateExchange: 'Päivitä hakemus',
    exchangeStatus: {
      submitted: 'Vastaanotettu, odottaa käsittelyä',
      verified: 'Vahvistettu, odottaa huonetta',
      waitlisted: 'Jonossa',
      allocated: 'Huone on myönnetty',
      rejected: 'Ei onnistunut',
      cancelled: 'Peruttu',
    },
    allocatedTo: 'Huoneesi',
    cancelExchange: 'Peru hakemus',
    dateError: 'Lähtöpäivän on oltava saapumispäivän jälkeen.',
    letterMissing: 'Lataa hyväksymiskirjeesi.',
    exchangeSaved: 'Hakemus tallennettu.',
  },
);
