import { defineSection } from './define';

export const bank = defineSection(
  {
    tab: 'Purchases',
    title: 'Shared purchases from your bank',
    lede: 'Connect your bank read-only, pick the small purchases you made for the flat, and split them in one tap. We only keep small outgoing purchases and incoming transfers from the last 60 days, and only you can see them.',
    off: 'Bank connection is not switched on yet.',
    connect: 'Connect my bank',
    chooseBank: 'Choose your bank',
    connectedTo: 'Connected',
    account: 'Account',
    lastSync: 'Last synced',
    never: 'never',
    sync: 'Sync purchases',
    synced: 'Synced. {n} new.',
    disconnect: 'Disconnect and delete the data',
    disconnected: 'Disconnected. The synced purchases were deleted.',
    consentEnds: 'Access until',
    expired: 'Your bank access has expired. Connect again.',
    purchasesHeading: 'Purchases you can share',
    noPurchases: 'Nothing to share right now. Sync to fetch your latest purchases.',
    limitNote: 'Only purchases up to {limit} are kept here.',
    share: 'Share with the flat',
    category: 'What was it',
    splitWith: 'Split with',
    everyone: 'Everyone in the flat',
    ignore: 'Not for the flat',
    shared: 'Shared',
    creditsHeading: 'Payments from flatmates',
    creditsLede: 'When a flatmate pays you back, we spot it. Confirm to mark their share as paid.',
    noCredits: 'No matching payments found.',
    markPaid: 'Mark {name} as paid',
    from: 'from',
    error: 'Something went wrong. Please try again.',
    errors: {
      bank_failed: 'The bank connection did not complete. Please try again.',
      bank_off: 'Bank connection is not switched on yet.',
    },
    // Admin
    admin: {
      title: 'Housing settings',
      lede: 'Rents at Kuopas are all-inclusive, so the bill splitter is limited to small shared purchases by default.',
      splitterHeading: 'Bill splitter',
      mode: 'What can flats split',
      modeMicro: 'Only small shared purchases (recommended)',
      modeAll: 'Any bill, including electricity and Wi-Fi',
      limit: 'Largest shared purchase (EUR)',
      save: 'Save',
      saved: 'Saved.',
      bankHeading: 'Bank connection',
      bankMode: 'Provider',
      bankStates: { off: 'Not connected. Set OPENBANKING_PROVIDER and its keys to switch it on.', mock: 'Test mode with fake transactions (development only).', enablebanking: 'Enable Banking' },
    },
  },
  {
    tab: 'Ostokset',
    title: 'Yhteiset ostokset pankistasi',
    lede: 'Yhdistä pankkisi vain lukuoikeudella, valitse asuntoon tekemäsi pienet ostokset ja jaa ne yhdellä napautuksella. Säilytämme vain pienet ostot ja saapuneet tilisiirrot 60 päivän ajalta, ja vain sinä näet ne.',
    off: 'Pankkiyhteyttä ei ole vielä otettu käyttöön.',
    connect: 'Yhdistä pankkini',
    chooseBank: 'Valitse pankkisi',
    connectedTo: 'Yhdistetty',
    account: 'Tili',
    lastSync: 'Viimeksi haettu',
    never: 'ei koskaan',
    sync: 'Hae ostokset',
    synced: 'Haettu. {n} uutta.',
    disconnect: 'Katkaise yhteys ja poista tiedot',
    disconnected: 'Yhteys katkaistu. Haetut ostokset poistettiin.',
    consentEnds: 'Käyttöoikeus voimassa',
    expired: 'Pankkioikeutesi on vanhentunut. Yhdistä uudelleen.',
    purchasesHeading: 'Jaettavissa olevat ostokset',
    noPurchases: 'Ei jaettavaa juuri nyt. Hae uusimmat ostoksesi.',
    limitNote: 'Tähän tallennetaan vain enintään {limit} ostokset.',
    share: 'Jaa asunnon kanssa',
    category: 'Mikä se oli',
    splitWith: 'Jaetaan kesken',
    everyone: 'Kaikki asunnossa',
    ignore: 'Ei asuntoa varten',
    shared: 'Jaettu',
    creditsHeading: 'Kämppisten maksut',
    creditsLede: 'Kun kämppis maksaa sinulle takaisin, huomaamme sen. Vahvista merkitäksesi hänen osuutensa maksetuksi.',
    noCredits: 'Täsmääviä maksuja ei löytynyt.',
    markPaid: 'Merkitse {name} maksaneeksi',
    from: 'lähettäjä',
    error: 'Jokin meni pieleen. Yritä uudelleen.',
    errors: {
      bank_failed: 'Pankkiyhteys ei onnistunut. Yritä uudelleen.',
      bank_off: 'Pankkiyhteyttä ei ole vielä otettu käyttöön.',
    },
    admin: {
      title: 'Asumisasetukset',
      lede: 'Kuopaksen vuokrat sisältävät kulut, joten laskujen jakaja on oletuksena rajattu pieniin yhteisostoksiin.',
      splitterHeading: 'Laskujen jakaja',
      mode: 'Mitä asunnot voivat jakaa',
      modeMicro: 'Vain pienet yhteisostokset (suositus)',
      modeAll: 'Mikä tahansa lasku, myös sähkö ja Wi-Fi',
      limit: 'Suurin yhteisostos (EUR)',
      save: 'Tallenna',
      saved: 'Tallennettu.',
      bankHeading: 'Pankkiyhteys',
      bankMode: 'Palveluntarjoaja',
      bankStates: { off: 'Ei yhdistetty. Ota käyttöön asettamalla OPENBANKING_PROVIDER ja sen avaimet.', mock: 'Testitila keksityillä tapahtumilla (vain kehitykseen).', enablebanking: 'Enable Banking' },
    },
  },
);
