import { defineSection } from './define';

export const flat = defineSection(
  {
    tabs: { cleaning: 'Cleaning', agreement: 'Agreement', transfer: 'Need a change?' },
    cleaning: {
      title: 'Shared cleaning checklist',
      lede: 'A fresh list every Monday. Tick a task when you have done it so everyone can see the flat is being looked after.',
      setup: 'Set up the checklist',
      setupBody: 'Start with a standard list for the kitchen, bathroom and hall. You can add or remove tasks afterwards.',
      areas: { kitchen: 'Kitchen', bathroom: 'Bathroom', hall: 'Hall', other: 'Other' },
      template: {
        'kitchen.counters': 'Wipe counters and stove',
        'kitchen.dishes': 'Dishes washed, sink clear',
        'kitchen.trash': 'Trash and recycling out',
        'kitchen.floor': 'Sweep and mop the floor',
        'kitchen.fridge': 'Clear old food from the fridge',
        'bathroom.toilet': 'Clean toilet and sink',
        'bathroom.shower': 'Clean the shower and drain',
        'bathroom.floor': 'Mop the floor',
        'bathroom.trash': 'Empty the bathroom bin',
        'hall.shoes': 'Tidy shoes and coats',
        'hall.floor': 'Sweep the hall',
      },
      thisWeek: 'This week',
      done: '{n} of {m} done',
      doneBy: 'Done by',
      undo: 'Undo',
      mark: 'Mark done',
      last4: 'Last four weeks',
      contribution: 'tasks done',
      addHeading: 'Add a task',
      taskPlaceholder: 'For example: Wipe the microwave',
      add: 'Add',
      remove: 'Remove',
      none: 'No tasks yet.',
    },
    agreement: {
      title: 'Flat agreement',
      lede: 'Agree the house rules once, in writing, so small things do not become big arguments. Everyone in the flat has to sign.',
      onlyShared: 'Flat agreements are for shared flats with two or more residents.',
      active: 'Active agreement',
      draft: 'Waiting for signatures',
      version: 'Version',
      signedBy: 'Signed by',
      waitingFor: 'Waiting for',
      sign: 'Sign',
      you: 'You',
      propose: 'Propose an agreement',
      proposeLede: 'Choose one option for every rule. Your flatmates get a notification and can sign or suggest a new version.',
      extra: 'Anything else you agree on (optional)',
      submit: 'Send for signing',
      change: 'Propose changes',
      none: 'No agreement yet.',
      incomplete: 'Please choose an option for every rule.',
      needsSignature: 'A new flatmate still needs to sign.',
      clauses: {
        quietHours: { title: 'Quiet hours', options: { '22-07': '22:00 to 07:00', '23-07': '23:00 to 07:00', '00-08': '00:00 to 08:00', flex: 'Flexible, we tell each other' } },
        guests: { title: 'Guests during the day', options: { ask: 'Ask the flat first', notice: 'Tell the flat beforehand', free: 'Free to invite' } },
        overnight: { title: 'Overnight guests', options: { none: 'None', one: 'Up to one night a week', two: 'Up to two nights a week', ask: 'Ask the flat each time' } },
        dishes: { title: 'Dishes', options: { same_day: 'Washed the same day', within_24h: 'Washed within 24 hours', rota: 'Weekly dish rota' } },
        kitchen: { title: 'Kitchen cleaning', options: { own: 'Everyone cleans their own mess', weekly_rota: 'Weekly rota', checklist: 'Shared checklist' } },
        bathroom: { title: 'Bathroom cleaning', options: { weekly_rota: 'Weekly rota', checklist: 'Shared checklist', own: 'Everyone cleans after themselves' } },
        supplies: { title: 'Shared supplies (soap, paper, coffee)', options: { split: 'Split the cost equally', own: 'Everyone buys their own', rotate: 'Take turns buying' } },
        food: { title: 'Food', options: { own: 'Everyone has their own', staples: 'Share basics like oil and salt', all: 'Share most things' } },
        smoking: { title: 'Smoking', options: { none: 'Not in the flat or the balcony', balcony: 'Only on the balcony' } },
        music: { title: 'Music and TV', options: { headphones: 'Headphones after quiet hours', moderate: 'Moderate volume', free: 'Free, within quiet hours' } },
      },
    },
    transfer: {
      title: 'Need a change?',
      lede: 'Moving to another flat is possible, but most problems in shared flats can be fixed sooner. Try these first. If they do not help, tell us and we will take it seriously.',
      safetyNote: 'If you feel unsafe, skip everything below and contact Kuopas straight away.',
      triedHeading: 'Before a transfer',
      agreementStep: 'Agree house rules together',
      agreementDone: 'Your flat has an active agreement.',
      agreementTodo: 'Set up a flat agreement.',
      cleaningStep: 'Use the shared cleaning checklist',
      cleaningNone: 'No checklist yet.',
      cleaningRate: 'completed over the last four weeks',
      open: 'Open',
      mediationStep: 'Ask Kuopas to help',
      mediationBody: 'A Kuopas manager talks it through with your flat. You stay where you are while it is sorted out.',
      askMediation: 'Ask for mediation',
      requestHeading: 'Request a transfer',
      reason: 'What is the main problem',
      reasons: { dirty_kitchen: 'Kitchen or bathroom is not kept clean', noise: 'Noise', conflict: 'Conflict with a flatmate', safety: 'I feel unsafe', other: 'Something else' },
      wants: 'What would you like',
      wantsOptions: { studio: 'A studio (yksiö)', other_shared: 'Another shared flat', any: 'Anything that suits' },
      description: 'Tell us what is happening',
      submit: 'Send transfer request',
      incomplete: 'Please fill in every field.',
      sent: 'Your request was sent. A manager will read it.',
      yourRequest: 'Your request',
      status: { open: 'Waiting', mediation: 'Mediation', approved: 'Approved', declined: 'Not possible now', resolved: 'Resolved', withdrawn: 'Withdrawn' },
      position: 'Place in the studio queue',
      staffNote: 'Note from Kuopas',
      withdraw: 'Withdraw request',
    },
    staff: {
      nav: 'Flats',
      title: 'Shared flats',
      lede: 'Which shared flats need attention before a resident asks to move out. The score adds up warning signs, so start at the top.',
      resident: 'residents',
      risk: 'Risk',
      flags: {
        noAgreement: 'No flat agreement',
        partialAgreement: 'Agreement not fully signed',
        noChecklist: 'No cleaning checklist',
        lowChecklist: 'Cleaning checklist mostly undone',
        overdueChores: 'Overdue chores',
        complaints: 'Recent noise or other complaints',
        transfer: 'Open transfer request',
      },
      healthy: 'No warning signs',
      nudge: 'Nudge the flat',
      nudged: 'Nudge sent.',
      nudgeBody: 'Kuopas suggests setting up your flat agreement and cleaning checklist',
      none: 'No shared flats yet.',
      agreement: 'Agreement',
      agreementStates: { none: 'None', draft: 'Waiting for signatures', active: 'Active' },
      cleaning: 'Cleaning (2 weeks)',
      overdue: 'overdue chores',
      complaintsLabel: 'complaints (30 days)',
      queueHeading: 'Transfer requests',
      queueLede: 'Studio and transfer requests in the order they arrived. Mediation first where a flat has not tried the tools.',
      queueNone: 'No open transfer requests.',
      triedAgreement: 'Flat agreement',
      yes: 'Yes',
      no: 'No',
      checklist: 'Checklist',
      position: 'Studio queue',
      reasons: { dirty_kitchen: 'Cleanliness', noise: 'Noise', conflict: 'Conflict', safety: 'Safety', other: 'Other' },
      wants: { studio: 'Studio', other_shared: 'Another shared flat', any: 'Anything' },
      startMediation: 'Start mediation',
      approve: 'Approve and move',
      approveOnly: 'Approve, no home yet',
      decline: 'Decline',
      resolved: 'Resolved',
      note: 'Note to the resident (optional)',
      chooseUnit: 'Move to (optional)',
      noUnit: 'No home yet',
      stats: 'Resolved without a move',
      status: { open: 'Waiting', mediation: 'Mediation', approved: 'Approved', declined: 'Declined', resolved: 'Resolved', withdrawn: 'Withdrawn' },
    },
  },
  {
    tabs: { cleaning: 'Siivous', agreement: 'Sopimus', transfer: 'Tarvitsetko muutosta?' },
    cleaning: {
      title: 'Yhteinen siivouslista',
      lede: 'Uusi lista joka maanantai. Merkitse tehtävä tehdyksi, kun olet tehnyt sen, jotta kaikki näkevät asunnon olevan hoidettu.',
      setup: 'Ota lista käyttöön',
      setupBody: 'Aloita valmiilla listalla keittiölle, kylpyhuoneelle ja eteiselle. Voit lisätä ja poistaa tehtäviä myöhemmin.',
      areas: { kitchen: 'Keittiö', bathroom: 'Kylpyhuone', hall: 'Eteinen', other: 'Muu' },
      template: {
        'kitchen.counters': 'Pyyhi työtasot ja liesi',
        'kitchen.dishes': 'Astiat pesty, allas tyhjä',
        'kitchen.trash': 'Roskat ja kierrätys ulos',
        'kitchen.floor': 'Lakaise ja moppaa lattia',
        'kitchen.fridge': 'Poista vanhat ruoat jääkaapista',
        'bathroom.toilet': 'Puhdista wc ja pesuallas',
        'bathroom.shower': 'Puhdista suihku ja lattiakaivo',
        'bathroom.floor': 'Moppaa lattia',
        'bathroom.trash': 'Tyhjennä kylpyhuoneen roskis',
        'hall.shoes': 'Järjestä kengät ja takit',
        'hall.floor': 'Lakaise eteinen',
      },
      thisWeek: 'Tämä viikko',
      done: '{n} / {m} tehty',
      doneBy: 'Tehnyt',
      undo: 'Kumoa',
      mark: 'Merkitse tehdyksi',
      last4: 'Viimeiset neljä viikkoa',
      contribution: 'tehtävää tehty',
      addHeading: 'Lisää tehtävä',
      taskPlaceholder: 'Esimerkiksi: Pyyhi mikroaaltouuni',
      add: 'Lisää',
      remove: 'Poista',
      none: 'Ei vielä tehtäviä.',
    },
    agreement: {
      title: 'Asuntosopimus',
      lede: 'Sopikaa talon säännöt kerran kirjallisesti, jotta pienet asiat eivät kasva isoiksi riidoiksi. Kaikkien asunnon asukkaiden on allekirjoitettava.',
      onlyShared: 'Asuntosopimukset on tarkoitettu soluasunnoille, joissa on vähintään kaksi asukasta.',
      active: 'Voimassa oleva sopimus',
      draft: 'Odottaa allekirjoituksia',
      version: 'Versio',
      signedBy: 'Allekirjoittaneet',
      waitingFor: 'Odottaa',
      sign: 'Allekirjoita',
      you: 'Sinä',
      propose: 'Ehdota sopimusta',
      proposeLede: 'Valitse yksi vaihtoehto jokaiseen sääntöön. Kämppiksesi saavat ilmoituksen ja voivat allekirjoittaa tai ehdottaa uutta versiota.',
      extra: 'Muuta, mistä sovitte (valinnainen)',
      submit: 'Lähetä allekirjoitettavaksi',
      change: 'Ehdota muutoksia',
      none: 'Ei vielä sopimusta.',
      incomplete: 'Valitse vaihtoehto jokaiseen sääntöön.',
      needsSignature: 'Uuden kämppiksen on vielä allekirjoitettava.',
      clauses: {
        quietHours: { title: 'Hiljaiset tunnit', options: { '22-07': '22.00 - 07.00', '23-07': '23.00 - 07.00', '00-08': '00.00 - 08.00', flex: 'Joustava, kerromme toisillemme' } },
        guests: { title: 'Vieraat päivällä', options: { ask: 'Kysytään ensin asunnolta', notice: 'Kerrotaan etukäteen', free: 'Saa kutsua vapaasti' } },
        overnight: { title: 'Yövieraat', options: { none: 'Ei lainkaan', one: 'Enintään yksi yö viikossa', two: 'Enintään kaksi yötä viikossa', ask: 'Kysytään joka kerta' } },
        dishes: { title: 'Astiat', options: { same_day: 'Pestään samana päivänä', within_24h: 'Pestään 24 tunnin sisällä', rota: 'Viikoittainen astiavuoro' } },
        kitchen: { title: 'Keittiön siivous', options: { own: 'Jokainen siivoaa omat jälkensä', weekly_rota: 'Viikoittainen vuorolista', checklist: 'Yhteinen tarkistuslista' } },
        bathroom: { title: 'Kylpyhuoneen siivous', options: { weekly_rota: 'Viikoittainen vuorolista', checklist: 'Yhteinen tarkistuslista', own: 'Jokainen siivoaa jälkensä' } },
        supplies: { title: 'Yhteiset tarvikkeet (saippua, paperi, kahvi)', options: { split: 'Jaetaan kulut tasan', own: 'Jokainen ostaa omansa', rotate: 'Ostetaan vuorotellen' } },
        food: { title: 'Ruoka', options: { own: 'Jokaisella on omansa', staples: 'Jaetaan perustarvikkeet kuten öljy ja suola', all: 'Jaetaan suurin osa' } },
        smoking: { title: 'Tupakointi', options: { none: 'Ei asunnossa eikä parvekkeella', balcony: 'Vain parvekkeella' } },
        music: { title: 'Musiikki ja tv', options: { headphones: 'Kuulokkeet hiljaisten tuntien jälkeen', moderate: 'Kohtuullinen äänenvoimakkuus', free: 'Vapaasti hiljaisten tuntien ulkopuolella' } },
      },
    },
    transfer: {
      title: 'Tarvitsetko muutosta?',
      lede: 'Toiseen asuntoon muuttaminen on mahdollista, mutta useimmat soluasuntojen ongelmat voi ratkaista nopeammin. Kokeile näitä ensin. Jos ne eivät auta, kerro meille ja otamme asian vakavasti.',
      safetyNote: 'Jos tunnet olosi turvattomaksi, ohita kaikki alla oleva ja ota heti yhteyttä Kuopakseen.',
      triedHeading: 'Ennen siirtoa',
      agreementStep: 'Sopikaa säännöt yhdessä',
      agreementDone: 'Asunnossanne on voimassa oleva sopimus.',
      agreementTodo: 'Tehkää asuntosopimus.',
      cleaningStep: 'Käyttäkää yhteistä siivouslistaa',
      cleaningNone: 'Listaa ei vielä ole.',
      cleaningRate: 'tehty viimeisen neljän viikon aikana',
      open: 'Avaa',
      mediationStep: 'Pyydä Kuopasta auttamaan',
      mediationBody: 'Kuopaksen isännöitsijä käy asian läpi asuntonne kanssa. Pysyt nykyisessä asunnossa, kun asiaa selvitetään.',
      askMediation: 'Pyydä sovittelua',
      requestHeading: 'Pyydä siirtoa',
      reason: 'Mikä on pääongelma',
      reasons: { dirty_kitchen: 'Keittiötä tai kylpyhuonetta ei siivota', noise: 'Melu', conflict: 'Riita kämppiksen kanssa', safety: 'Tunnen oloni turvattomaksi', other: 'Jokin muu' },
      wants: 'Mitä toivot',
      wantsOptions: { studio: 'Yksiö', other_shared: 'Toinen soluasunto', any: 'Mikä tahansa sopiva' },
      description: 'Kerro, mitä tapahtuu',
      submit: 'Lähetä siirtopyyntö',
      incomplete: 'Täytä jokainen kenttä.',
      sent: 'Pyyntösi lähetettiin. Isännöitsijä lukee sen.',
      yourRequest: 'Pyyntösi',
      status: { open: 'Odottaa', mediation: 'Sovittelu', approved: 'Hyväksytty', declined: 'Ei nyt mahdollista', resolved: 'Ratkaistu', withdrawn: 'Peruttu' },
      position: 'Sija yksiöjonossa',
      staffNote: 'Viesti Kuopakselta',
      withdraw: 'Peru pyyntö',
    },
    staff: {
      nav: 'Solut',
      title: 'Soluasunnot',
      lede: 'Mitkä soluasunnot tarvitsevat huomiota ennen kuin asukas pyytää siirtoa. Pisteet laskevat yhteen varoitusmerkit, joten aloita ylhäältä.',
      resident: 'asukasta',
      risk: 'Riski',
      flags: {
        noAgreement: 'Ei asuntosopimusta',
        partialAgreement: 'Sopimusta ei ole allekirjoitettu kokonaan',
        noChecklist: 'Ei siivouslistaa',
        lowChecklist: 'Siivouslista pääosin tekemättä',
        overdueChores: 'Myöhässä olevia askareita',
        complaints: 'Äskettäisiä melu- tai muita valituksia',
        transfer: 'Avoin siirtopyyntö',
      },
      healthy: 'Ei varoitusmerkkejä',
      nudge: 'Muistuta asuntoa',
      nudged: 'Muistutus lähetetty.',
      nudgeBody: 'Kuopas ehdottaa asuntosopimuksen ja siivouslistan käyttöönottoa',
      none: 'Ei vielä soluasuntoja.',
      agreement: 'Sopimus',
      agreementStates: { none: 'Ei ole', draft: 'Odottaa allekirjoituksia', active: 'Voimassa' },
      cleaning: 'Siivous (2 viikkoa)',
      overdue: 'myöhässä olevaa askaretta',
      complaintsLabel: 'valitusta (30 pv)',
      queueHeading: 'Siirtopyynnöt',
      queueLede: 'Yksiö- ja siirtopyynnöt saapumisjärjestyksessä. Sovittelu ensin, jos asunto ei ole kokeillut työkaluja.',
      queueNone: 'Ei avoimia siirtopyyntöjä.',
      triedAgreement: 'Asuntosopimus',
      yes: 'Kyllä',
      no: 'Ei',
      checklist: 'Siivouslista',
      position: 'Yksiöjono',
      reasons: { dirty_kitchen: 'Siisteys', noise: 'Melu', conflict: 'Riita', safety: 'Turvallisuus', other: 'Muu' },
      wants: { studio: 'Yksiö', other_shared: 'Toinen soluasunto', any: 'Mikä tahansa' },
      startMediation: 'Aloita sovittelu',
      approve: 'Hyväksy ja siirrä',
      approveOnly: 'Hyväksy, ei vielä kotia',
      decline: 'Hylkää',
      resolved: 'Ratkaistu',
      note: 'Viesti asukkaalle (valinnainen)',
      chooseUnit: 'Siirrä (valinnainen)',
      noUnit: 'Ei vielä kotia',
      stats: 'Ratkaistu ilman muuttoa',
      status: { open: 'Odottaa', mediation: 'Sovittelu', approved: 'Hyväksytty', declined: 'Hylätty', resolved: 'Ratkaistu', withdrawn: 'Peruttu' },
    },
  },
);
