import { defineSection } from './define';

export const inspection = defineSection(
  {
    tab: 'Inspection',
    title: 'Move-in and move-out inspection',
    lede: 'Record the condition of your room and the shared spaces with photos. This is your proof when you move out, and it helps Kuopas fix problems early.',
    depositNote: 'A dated record of what you found on arrival protects your deposit. Anything you record now cannot be charged to you later.',
    kinds: { move_in: 'Move-in inspection', move_out: 'Move-out inspection' },
    start: { move_in: 'Start move-in inspection', move_out: 'Start move-out inspection' },
    none: 'No inspections yet.',
    open: 'Open',
    due: 'Due',
    status: {
      draft: 'In progress',
      submitted: 'Submitted',
      acknowledged: 'Acknowledged by Kuopas',
      changes_requested: 'Kuopas asked for changes',
    },
    areas: {
      room: 'My room',
      kitchen: 'Shared kitchen',
      bathroom: 'Bathroom and toilet',
      hall: 'Hall and storage',
      balcony: 'Balcony or patio',
    },
    items: {
      'room.walls': 'Walls',
      'room.ceiling': 'Ceiling',
      'room.floor': 'Floor',
      'room.windows': 'Windows',
      'room.door': 'Door and lock',
      'room.furniture': 'Furniture',
      'room.electrics': 'Sockets and lights',
      'kitchen.counters': 'Counters and cabinets',
      'kitchen.sink': 'Sink and taps',
      'kitchen.stove': 'Stove and oven',
      'kitchen.fridge': 'Fridge and freezer',
      'kitchen.floor': 'Floor',
      'kitchen.walls': 'Walls',
      'bathroom.toilet': 'Toilet',
      'bathroom.shower': 'Shower',
      'bathroom.sink': 'Sink and mirror',
      'bathroom.floor': 'Floor and drain',
      'bathroom.ventilation': 'Ventilation',
      'hall.floor': 'Floor',
      'hall.walls': 'Walls',
      'hall.closet': 'Closet',
      'balcony.floor': 'Floor',
      'balcony.railing': 'Railing',
      'balcony.door': 'Door',
    },
    conditions: {
      unset: 'Choose',
      ok: 'Good condition',
      minor: 'Minor wear',
      damaged: 'Damaged',
      missing: 'Missing',
      na: 'Not applicable',
    },
    notePlaceholder: 'Describe what you see',
    photo: 'Photo',
    replacePhoto: 'Replace photo',
    saveArea: 'Save this area',
    saved: 'Saved',
    progress: '{n} of {m} checked',
    submit: 'Submit inspection',
    submitHelp: 'Once submitted the record is locked and gets a fingerprint, so nobody can change it later. Every issue needs a note or a photo.',
    errors: {
      incomplete: 'Check every item first, use Not applicable if something does not exist.',
      evidence: 'Every item that is not in good condition needs a note or a photo.',
    },
    justSubmitted: 'Submitted. Your record is locked and stored.',
    record: 'Record',
    fingerprint: 'Fingerprint (SHA-256)',
    submittedOn: 'Submitted',
    acknowledgedOn: 'Acknowledged',
    staffNote: 'Note from Kuopas',
    issues: 'Issues recorded',
    locked: 'This record is locked.',
    changesHint: 'Update the items Kuopas mentioned and submit again.',
    // Staff
    staff: {
      title: 'Inspections',
      lede: 'Move-in and move-out records with photos. Acknowledge a record, ask for changes, or open a maintenance ticket from a recorded defect.',
      tabs: { submitted: 'To review', all: 'All' },
      none: 'No inspections.',
      resident: 'Resident',
      apartment: 'Apartment',
      issuesCount: 'issues',
      open: 'Open',
      acknowledge: 'Acknowledge',
      requestChanges: 'Ask for changes',
      note: 'Note to the resident (optional)',
      ticket: 'Open maintenance ticket',
      ticketOpened: 'Maintenance ticket opened.',
      compareHeading: 'Compared with the move-in record',
      compareNone: 'This resident has no submitted move-in record.',
      newDamage: 'New since move-in',
      alreadyThere: 'Already recorded at move-in',
      unchanged: 'No new damage found.',
      moveIn: 'Move-in',
      moveOut: 'Move-out',
      allItems: 'All items',
      recorded: 'Recorded damage at move-in',
      recordedLede: 'Defects residents documented when they arrived. Useful for planning repairs and for deposit disputes.',
      noRecorded: 'No move-in defects recorded yet.',
    },
  },
  {
    tab: 'Tarkastus',
    title: 'Muuttotarkastus',
    lede: 'Kirjaa huoneesi ja yhteisten tilojen kunto valokuvin. Tämä on todisteesi muuttaessasi pois, ja se auttaa Kuopasta korjaamaan ongelmat ajoissa.',
    depositNote: 'Päivätty kirjaus siitä, mitä löysit saapuessasi, suojaa vakuuttasi. Mitä kirjaat nyt, sitä ei voi myöhemmin veloittaa sinulta.',
    kinds: { move_in: 'Sisäänmuuttotarkastus', move_out: 'Poismuuttotarkastus' },
    start: { move_in: 'Aloita sisäänmuuttotarkastus', move_out: 'Aloita poismuuttotarkastus' },
    none: 'Ei vielä tarkastuksia.',
    open: 'Avaa',
    due: 'Määräaika',
    status: {
      draft: 'Kesken',
      submitted: 'Lähetetty',
      acknowledged: 'Kuopas on kuitannut',
      changes_requested: 'Kuopas pyysi muutoksia',
    },
    areas: {
      room: 'Oma huoneeni',
      kitchen: 'Yhteinen keittiö',
      bathroom: 'Kylpyhuone ja wc',
      hall: 'Eteinen ja varasto',
      balcony: 'Parveke tai terassi',
    },
    items: {
      'room.walls': 'Seinät',
      'room.ceiling': 'Katto',
      'room.floor': 'Lattia',
      'room.windows': 'Ikkunat',
      'room.door': 'Ovi ja lukko',
      'room.furniture': 'Kalusteet',
      'room.electrics': 'Pistorasiat ja valot',
      'kitchen.counters': 'Työtasot ja kaapit',
      'kitchen.sink': 'Allas ja hanat',
      'kitchen.stove': 'Liesi ja uuni',
      'kitchen.fridge': 'Jääkaappi ja pakastin',
      'kitchen.floor': 'Lattia',
      'kitchen.walls': 'Seinät',
      'bathroom.toilet': 'Wc-istuin',
      'bathroom.shower': 'Suihku',
      'bathroom.sink': 'Pesuallas ja peili',
      'bathroom.floor': 'Lattia ja lattiakaivo',
      'bathroom.ventilation': 'Ilmanvaihto',
      'hall.floor': 'Lattia',
      'hall.walls': 'Seinät',
      'hall.closet': 'Vaatekaappi',
      'balcony.floor': 'Lattia',
      'balcony.railing': 'Kaide',
      'balcony.door': 'Ovi',
    },
    conditions: {
      unset: 'Valitse',
      ok: 'Hyvässä kunnossa',
      minor: 'Vähäistä kulumaa',
      damaged: 'Vaurioitunut',
      missing: 'Puuttuu',
      na: 'Ei koske',
    },
    notePlaceholder: 'Kuvaile, mitä näet',
    photo: 'Kuva',
    replacePhoto: 'Vaihda kuva',
    saveArea: 'Tallenna tämä alue',
    saved: 'Tallennettu',
    progress: '{n} / {m} tarkistettu',
    submit: 'Lähetä tarkastus',
    submitHelp: 'Lähettämisen jälkeen kirjaus lukitaan ja sille lasketaan sormenjälki, jotta kukaan ei voi muuttaa sitä myöhemmin. Jokaiseen ongelmaan tarvitaan kuvaus tai kuva.',
    errors: {
      incomplete: 'Tarkista ensin jokainen kohta, käytä Ei koske, jos jotain ei ole.',
      evidence: 'Jokaiseen kohtaan, joka ei ole hyvässä kunnossa, tarvitaan kuvaus tai kuva.',
    },
    justSubmitted: 'Lähetetty. Kirjauksesi on lukittu ja tallennettu.',
    record: 'Kirjaus',
    fingerprint: 'Sormenjälki (SHA-256)',
    submittedOn: 'Lähetetty',
    acknowledgedOn: 'Kuitattu',
    staffNote: 'Viesti Kuopakselta',
    issues: 'Kirjatut ongelmat',
    locked: 'Tämä kirjaus on lukittu.',
    changesHint: 'Päivitä Kuopaksen mainitsemat kohdat ja lähetä uudelleen.',
    staff: {
      title: 'Tarkastukset',
      lede: 'Sisään- ja poismuuttokirjaukset kuvineen. Kuittaa kirjaus, pyydä muutoksia tai avaa huoltopyyntö kirjatusta viasta.',
      tabs: { submitted: 'Tarkistettavat', all: 'Kaikki' },
      none: 'Ei tarkastuksia.',
      resident: 'Asukas',
      apartment: 'Asunto',
      issuesCount: 'ongelmaa',
      open: 'Avaa',
      acknowledge: 'Kuittaa',
      requestChanges: 'Pyydä muutoksia',
      note: 'Viesti asukkaalle (valinnainen)',
      ticket: 'Avaa huoltopyyntö',
      ticketOpened: 'Huoltopyyntö avattu.',
      compareHeading: 'Verrattuna sisäänmuuttokirjaukseen',
      compareNone: 'Asukkaalla ei ole lähetettyä sisäänmuuttokirjausta.',
      newDamage: 'Uutta sisäänmuuton jälkeen',
      alreadyThere: 'Kirjattu jo sisäänmuutossa',
      unchanged: 'Uusia vaurioita ei löytynyt.',
      moveIn: 'Sisäänmuutto',
      moveOut: 'Poismuutto',
      allItems: 'Kaikki kohdat',
      recorded: 'Sisäänmuutossa kirjatut vauriot',
      recordedLede: 'Viat, jotka asukkaat dokumentoivat saapuessaan. Hyödyllinen korjausten suunnittelussa ja vakuusriidoissa.',
      noRecorded: 'Sisäänmuuttoviat eivät ole vielä kirjattuina.',
    },
  },
);
