import { defineSection } from './define';

export const intake = defineSection(
  {
    homes: {
      title: 'Homes and applications',
      lede: 'Describe each apartment and choose which ones applicants can apply for. Nothing is listed to applicants until you open it.',
      building: 'Building',
      choose: 'Choose a building',
      kind: 'Type',
      kinds: { unspecified: 'Not set', solu: 'Shared flat (soluasunto)', studio: 'Studio (yksiö)', other: 'Other apartment' },
      rooms: 'Rooms',
      furnished: 'Furnished',
      temporary: 'Temporary exchange housing',
      open: 'Open for applications',
      availableFrom: 'Available from',
      save: 'Save',
      apartments: 'Apartments',
      none: 'No apartments in this building yet. Add them below.',
      residents: 'residents',
      addHeading: 'Add apartments',
      addLede: 'One code per line or separated by commas. The floor is taken from the first digit of the code.',
      stairwell: 'Stairwell',
      codes: 'Apartment codes',
      add: 'Add apartments',
      added: 'Added',
      delete: 'Delete',
      deleteBlocked: 'Has residents',
    },
    applications: {
      title: 'Housing applications',
      lede: 'Pods and individuals applying for a home. Everyone in a pod is verified. Offer a home, or allocate it straight away.',
      tabOpen: 'Open',
      tabDecided: 'Decided',
      none: 'No applications.',
      pod: 'Pod',
      members: 'Members',
      groupFit: 'Group compatibility',
      lowest: 'lowest pair',
      clash: 'Dealbreaker clash inside the pod',
      residentFit: 'Fit with current residents',
      freeRooms: 'free rooms',
      needs: 'needs',
      message: 'Message',
      note: 'Note to applicants (optional)',
      offer: 'Offer the home',
      allocate: 'Allocate now',
      reject: 'Reject',
      status: {
        submitted: 'Waiting',
        offered: 'Offered',
        accepted: 'Accepted',
        declined: 'Declined by applicants',
        withdrawn: 'Withdrawn',
        rejected: 'Rejected',
        housed: 'Moved in',
      },
      verified: 'Verified',
      notVerified: 'Not verified',
      leaseNote: 'After allocating, create each person a lease on the Leases page.',
    },
    exchange: {
      title: 'Exchange student intake',
      lede: 'Verify exchange applications, then allocate them to temporary furnished apartments in arrival order.',
      quota: 'Temporary furnished apartments',
      quotaFree: 'free for the period',
      counts: { submitted: 'Received', verified: 'Verified', waitlisted: 'Waiting list', allocated: 'Allocated', rejected: 'Rejected', cancelled: 'Cancelled' },
      tabs: { queue: 'Queue', allocated: 'Allocated', closed: 'Closed' },
      none: 'No applications.',
      university: 'Home university',
      arrives: 'Arrives',
      leaves: 'Leaves',
      wants: 'Wants',
      wantsOptions: { any: 'Anything', solu: 'Shared flat room', studio: 'Studio' },
      letter: 'Acceptance letter',
      noLetter: 'No letter uploaded',
      verify: 'Verify',
      reject: 'Reject',
      waitlist: 'Waiting list',
      allocate: 'Allocate',
      suggest: 'Suggested apartment',
      noSuggestion: 'No free apartment for these dates',
      chooseUnit: 'Choose an apartment',
      rent: 'Monthly rent (EUR)',
      deposit: 'Deposit (EUR)',
      bulkHeading: 'Allocate everyone verified',
      bulkLede: 'Goes through verified and waiting applications in arrival order and gives each the first suitable free apartment. Anyone who does not fit goes on the waiting list.',
      bulkButton: 'Allocate automatically',
      bulkResult: 'Allocated {a}, waiting list {w}.',
      statusNote: 'Note',
      needRent: 'Enter the monthly rent first.',
    },
  },
  {
    homes: {
      title: 'Kodit ja hakemukset',
      lede: 'Kuvaile jokainen asunto ja valitse, mihin hakijat voivat hakea. Hakijoille ei näytetä mitään ennen kuin avaat sen.',
      building: 'Talo',
      choose: 'Valitse talo',
      kind: 'Tyyppi',
      kinds: { unspecified: 'Ei asetettu', solu: 'Soluasunto', studio: 'Yksiö', other: 'Muu asunto' },
      rooms: 'Huoneita',
      furnished: 'Kalustettu',
      temporary: 'Tilapäinen vaihtoasuminen',
      open: 'Haettavissa',
      availableFrom: 'Vapautuu',
      save: 'Tallenna',
      apartments: 'Asunnot',
      none: 'Tässä talossa ei ole vielä asuntoja. Lisää ne alla.',
      residents: 'asukasta',
      addHeading: 'Lisää asuntoja',
      addLede: 'Yksi koodi per rivi tai pilkulla erotettuna. Kerros otetaan koodin ensimmäisestä numerosta.',
      stairwell: 'Rappu',
      codes: 'Asuntokoodit',
      add: 'Lisää asunnot',
      added: 'Lisätty',
      delete: 'Poista',
      deleteBlocked: 'Asukkaita',
    },
    applications: {
      title: 'Asumishakemukset',
      lede: 'Kotia hakevat ryhmät ja yksittäiset hakijat. Jokainen ryhmän jäsen on vahvistettu. Tarjoa koti tai myönnä se heti.',
      tabOpen: 'Avoimet',
      tabDecided: 'Ratkaistut',
      none: 'Ei hakemuksia.',
      pod: 'Ryhmä',
      members: 'Jäsenet',
      groupFit: 'Ryhmän sopivuus',
      lowest: 'heikoin pari',
      clash: 'Ristiriita ehdottomassa toiveessa ryhmän sisällä',
      residentFit: 'Sopivuus nykyisten asukkaiden kanssa',
      freeRooms: 'vapaata huonetta',
      needs: 'tarvitsee',
      message: 'Viesti',
      note: 'Viesti hakijoille (valinnainen)',
      offer: 'Tarjoa koti',
      allocate: 'Myönnä heti',
      reject: 'Hylkää',
      status: {
        submitted: 'Odottaa',
        offered: 'Tarjottu',
        accepted: 'Hyväksytty',
        declined: 'Hakijat hylkäsivät',
        withdrawn: 'Peruttu',
        rejected: 'Hylätty',
        housed: 'Muuttanut sisään',
      },
      verified: 'Vahvistettu',
      notVerified: 'Ei vahvistettu',
      leaseNote: 'Myöntämisen jälkeen luo jokaiselle vuokrasopimus Vuokrat-sivulla.',
    },
    exchange: {
      title: 'Vaihto-opiskelijoiden haku',
      lede: 'Vahvista vaihtohakemukset ja myönnä ne tilapäisiin kalustettuihin asuntoihin saapumisjärjestyksessä.',
      quota: 'Tilapäiset kalustetut asunnot',
      quotaFree: 'vapaana ajanjaksolle',
      counts: { submitted: 'Vastaanotettu', verified: 'Vahvistettu', waitlisted: 'Jonossa', allocated: 'Myönnetty', rejected: 'Hylätty', cancelled: 'Peruttu' },
      tabs: { queue: 'Jono', allocated: 'Myönnetyt', closed: 'Suljetut' },
      none: 'Ei hakemuksia.',
      university: 'Kotiyliopisto',
      arrives: 'Saapuu',
      leaves: 'Lähtee',
      wants: 'Toive',
      wantsOptions: { any: 'Mikä tahansa', solu: 'Huone soluasunnossa', studio: 'Yksiö' },
      letter: 'Hyväksymiskirje',
      noLetter: 'Kirjettä ei ole ladattu',
      verify: 'Vahvista',
      reject: 'Hylkää',
      waitlist: 'Jonoon',
      allocate: 'Myönnä',
      suggest: 'Ehdotettu asunto',
      noSuggestion: 'Näille päiville ei ole vapaata asuntoa',
      chooseUnit: 'Valitse asunto',
      rent: 'Kuukausivuokra (EUR)',
      deposit: 'Vakuus (EUR)',
      bulkHeading: 'Myönnä kaikille vahvistetuille',
      bulkLede: 'Käy läpi vahvistetut ja jonossa olevat hakemukset saapumisjärjestyksessä ja antaa jokaiselle ensimmäisen sopivan vapaan asunnon. Ne, joille ei löydy, siirtyvät jonoon.',
      bulkButton: 'Myönnä automaattisesti',
      bulkResult: 'Myönnetty {a}, jonossa {w}.',
      statusNote: 'Viesti',
      needRent: 'Syötä ensin kuukausivuokra.',
    },
  },
);
