import { defineSection } from './define';

export const safety = defineSection(
  {
    block: 'Block',
    unblock: 'Unblock',
    report: 'Report',
    reported: 'Reported',
    reportedNote: 'Thanks, a moderator will review it.',
    blockedBanner: 'You blocked this person. Their messages are hidden and you cannot message each other.',
    cannotMessage: 'You cannot message this person.',
    removed: 'Removed by a moderator',
    blockedUsers: 'Blocked people',
    blockedLede: 'You do not see messages, posts or comments from people you block, and they cannot message you.',
    noBlocked: 'You have not blocked anyone.',
    staffHeading: 'Reported direct and community messages',
    staffEmpty: 'No reported messages.',
    sender: 'Sender',
    reportedBy: 'Reported by',
    kinds: { direct: 'Direct message', community: 'Community' },
    remove: 'Remove message',
    dismiss: 'Dismiss',
  },
  {
    block: 'Estä',
    unblock: 'Poista esto',
    report: 'Ilmianna',
    reported: 'Ilmiannettu',
    reportedNote: 'Kiitos, moderaattori tarkistaa sen.',
    blockedBanner: 'Olet estänyt tämän henkilön. Hänen viestinsä on piilotettu, ettekä voi lähettää viestejä toisillenne.',
    cannotMessage: 'Et voi lähettää viestiä tälle henkilölle.',
    removed: 'Moderaattorin poistama',
    blockedUsers: 'Estetyt henkilöt',
    blockedLede: 'Et näe estämiesi henkilöiden viestejä, julkaisuja tai kommentteja, eivätkä he voi lähettää sinulle viestejä.',
    noBlocked: 'Et ole estänyt ketään.',
    staffHeading: 'Ilmiannetut yksityis- ja yhteisöviestit',
    staffEmpty: 'Ei ilmiannettuja viestejä.',
    sender: 'Lähettäjä',
    reportedBy: 'Ilmiantaja',
    kinds: { direct: 'Yksityisviesti', community: 'Yhteisö' },
    remove: 'Poista viesti',
    dismiss: 'Hylkää',
  },
);
