import { defineSection } from './define';

export const signing = defineSection(
  {
    methods: { suomifi: 'Suomi.fi e-Identification', exchange_letter: 'Exchange acceptance letter' },
    suomiHeading: 'Verify instantly with Suomi.fi',
    suomiLede: 'Sign in with your online banking codes or a mobile certificate. It proves who you are in seconds. Kuopas only stores an irreversible fingerprint of your identity, never your personal identity code.',
    suomiButton: 'Continue with Suomi.fi',
    errors: {
      suomifi_off: 'Suomi.fi login is not available yet.',
      suomifi_taken: 'That identity is already linked to another Kuopas account.',
      suomifi_mismatch: 'That identity does not match the one already linked to your account.',
      suomifi_failed: 'The Suomi.fi login did not complete. Please try again.',
    },
    pendingBadge: 'Signature needed',
    signNow: 'Review and sign',
    signed: 'Signed',
    title: 'Sign your lease',
    lede: 'Check the terms below, then sign with Suomi.fi. Your signature is tied to exactly these terms.',
    parties: 'Parties',
    landlord: 'Landlord',
    tenant: 'Tenant',
    premises: 'Apartment',
    term: 'Lease period',
    rent: 'Monthly rent',
    deposit: 'Deposit',
    upfront: 'Rent paid in advance',
    months: 'months',
    schedule: 'Rent schedule',
    due: 'due',
    termsNote: 'The general lease terms of Kuopas apply together with these terms.',
    termsLink: 'Read the general lease terms',
    fingerprint: 'Terms fingerprint (SHA-256)',
    signButton: 'Sign with Suomi.fi',
    signOff: 'Digital signing is not available yet. Ask Kuopas to sign on paper.',
    youSigned: 'You signed',
    via: 'with',
    awaitingStaff: 'Waiting for Kuopas to countersign.',
    staffSigned: 'Countersigned by Kuopas',
    inForce: 'The lease is in force.',
    legal: 'Signed using strong electronic identification. The fingerprint identifies exactly the terms you saw, so any later change would be detectable.',
    justSigned: 'Signed. A copy stays on this page.',
    notFound: 'This lease is not available for signing.',
    back: 'Back to my lease',
    staff: {
      require: 'Ask the resident to sign digitally with Suomi.fi',
      countersign: 'Countersign',
      signatures: 'Signatures',
      residentSigned: 'Resident signed',
      notSigned: 'Not signed yet',
      countersigned: 'Countersigned',
      pending: 'Waiting for signatures',
    },
  },
  {
    methods: { suomifi: 'Suomi.fi-tunnistus', exchange_letter: 'Vaihto-opiskelun hyväksymiskirje' },
    suomiHeading: 'Vahvista heti Suomi.fi:llä',
    suomiLede: 'Kirjaudu verkkopankkitunnuksilla tai mobiilivarmenteella. Se todistaa henkilöllisyytesi sekunneissa. Kuopas tallentaa vain peruuttamattoman tunnisteen henkilöllisyydestäsi, ei henkilötunnustasi.',
    suomiButton: 'Jatka Suomi.fi:llä',
    errors: {
      suomifi_off: 'Suomi.fi-kirjautuminen ei ole vielä käytettävissä.',
      suomifi_taken: 'Tämä henkilöllisyys on jo liitetty toiseen Kuopas-tiliin.',
      suomifi_mismatch: 'Henkilöllisyys ei vastaa tiliisi jo liitettyä.',
      suomifi_failed: 'Suomi.fi-kirjautuminen ei onnistunut. Yritä uudelleen.',
    },
    pendingBadge: 'Allekirjoitus tarvitaan',
    signNow: 'Tarkista ja allekirjoita',
    signed: 'Allekirjoitettu',
    title: 'Allekirjoita vuokrasopimuksesi',
    lede: 'Tarkista alla olevat ehdot ja allekirjoita Suomi.fi:llä. Allekirjoituksesi sidotaan täsmälleen näihin ehtoihin.',
    parties: 'Osapuolet',
    landlord: 'Vuokranantaja',
    tenant: 'Vuokralainen',
    premises: 'Asunto',
    term: 'Vuokra-aika',
    rent: 'Kuukausivuokra',
    deposit: 'Vakuus',
    upfront: 'Ennakkoon maksettava vuokra',
    months: 'kuukautta',
    schedule: 'Vuokra-aikataulu',
    due: 'erääntyy',
    termsNote: 'Kuopaksen yleiset vuokrausehdot koskevat näiden ehtojen lisäksi.',
    termsLink: 'Lue yleiset vuokrausehdot',
    fingerprint: 'Ehtojen sormenjälki (SHA-256)',
    signButton: 'Allekirjoita Suomi.fi:llä',
    signOff: 'Sähköinen allekirjoitus ei ole vielä käytettävissä. Pyydä Kuopasta allekirjoittamaan paperilla.',
    youSigned: 'Allekirjoitit',
    via: 'menetelmällä',
    awaitingStaff: 'Odottaa Kuopaksen vastaallekirjoitusta.',
    staffSigned: 'Kuopas on vastaallekirjoittanut',
    inForce: 'Vuokrasopimus on voimassa.',
    legal: 'Allekirjoitettu vahvalla sähköisellä tunnistautumisella. Sormenjälki yksilöi täsmälleen ne ehdot, jotka näit, joten myöhempi muutos olisi havaittavissa.',
    justSigned: 'Allekirjoitettu. Kopio pysyy tällä sivulla.',
    notFound: 'Tätä vuokrasopimusta ei voi allekirjoittaa.',
    back: 'Takaisin vuokrasopimukseeni',
    staff: {
      require: 'Pyydä vuokralaista allekirjoittamaan sähköisesti Suomi.fi:llä',
      countersign: 'Vastaallekirjoita',
      signatures: 'Allekirjoitukset',
      residentSigned: 'Vuokralainen allekirjoittanut',
      notSigned: 'Ei vielä allekirjoitettu',
      countersigned: 'Vastaallekirjoitettu',
      pending: 'Odottaa allekirjoituksia',
    },
  },
);
